### ISSUE TITLE
c2670.bench, list index out of range

### ISSUE THREAD

**Issue by xinqiaozhang** [AbdulRahmanAlHamali/python-circuit-testability-measures#1]
Hi there,
Thank you for your repo. It is a great help for my research. When I was using c2670.bench to measure the testability, it has an error saying that  "list index out of range". Do you have any idea about this? I changed the format based on the example.
```
Traceback (most recent call last):
  File "calculate_testability_measures.py", line 39, in <module>
    calculateTestabilityMeasures(InputFileName, OutputFileName)
  File "calculate_testability_measures.py", line 11, in calculateTestabilityMeasures
    levels = createLevelArrayFromCircuitDescription(circuitDescription)
  File "/home/x5zhang/ICCAD/SCOAP/python-circuit-testability-measures/src/create_level_array_from_circuit_description.py",line 11, in createLevelArrayFromCircuitDescription
    } for i in inputs
  File "/home/x5zhang/ICCAD/SCOAP/python-circuit-testability-measures/src/create_level_array_from_circuit_description.py",line 11, in <dictcomp>
    } for i in inputs
IndexError: list index out of range
```

**Comment by AbdulRahmanAlHamali** [comment]
Hi Joe,

I'm sorry but I made this many years ago as part of a university course project and uploaded it here for reference. I am not actively maintaining this

**Comment by shashidharBobbiti** [comment]
Hi sir,  I am not understanding how to run this code for benchmark circuits, can u suggest me
